<?php
/*** Definicao dos diretorios ***/
$DIR_DADOS= dirname(__FILE__) . '/dados/'; 
/*** $DIR_FOTOS= dirname(__DIR__) . '/Fotos/'; ***/
$DIR_FOTOS='../Fotos/';
$DIR_MODELOS= dirname(__FILE__) . '/modelos/';
$DIR_LANCAMENTOS= dirname(__DIR__) . '/Lanctos/';
$DIR_IMAGENS= dirname(__DIR__) . '/imagens/';
$DIR_ANEXOS= dirname(__DIR__) . '/Anexos/';

/*** Configuracao do cliente on-line ***/
//$LOGIN_CPFCNPJ='SIM';
//$LOGIN_EMAIL='SIM';
//$SENHA_DEFAULT="'123456'";
//$EXIBE_COND_TOTAL_DOCS='SIM';
//$EXIBE_COND_LANCTOS_FUTUROS='NAO';
//$EXIBE_OBS_COMERCIALIZACAO='SIM';
//$EXIBE_OBS_COMERC_PESSOA='SIM';
//$EXIBE_INADIMPL_SEPARADO='SIM';
$EXIBE_IMAGEM_LANCTO='SIM';
//$EXIBE_OBS_INADIMPLENCIA='SIM';
//$DIAS_VALIDADE_DOC_VENCIDO_LOC=30;
//$DIAS_VALIDADE_DOC_VENCIDO_COND=30;
//$SERVICOS_EXTRAS_COND='SIM';
//$EXIBE_IR_ANUAL='SIM';
//$PLANILHA_GAS_COND='SIM';
//$EXIBE_COND_ANEXOS='SIM';
$EXIBE_LISTA_CONDOMINOS='SIM';
//$BOLETOS_EM_ARVORE='SIM';
//$EXIBE_EXTRATOCOND_ATUAL='NAO'
//$PDF_DOC='SIM';
$MESES_NO_SITE_EXTRATOCOND=3;
$MESES_NO_SITE_BOLETOS=1;

/*** Configuracao de imagens ***/
//$THUMBNAILS_RESIZE='NAO';

/*** Cidades default na pesquisa de locacao e venda ***/
$CIDADE_LOC='PORTO ALEGRE';
$CIDADE_VENDA='PORTO ALEGRE';

/*** Configuracao da pesquisa de imoveis ***/
//$PESQUISA_GARAGEM='SIM';
//$EXIBE_ENDERECO_VENDA='NAO';
//$EXIBE_ENDERECO_LOCACAO='NAO';
$EXIBE_TODAS_CIDADES='SIM';
$EXIBE_RESID_COMERC_VENDA='NAO';
$EXIBE_RESID_COMERC_LOCACAO='NAO';
$EXIBE_TODOS_TIPOS='SIM';
$EXIBE_THUMBNAILS='SIM';
$LARGURA_THUMBNAILS_PESQUISA=200;
$EXIBE_THUMBNAILS_FOTOS='SIM';
$LARGURA_THUMBNAILS_FOTOS=80;
$CHAVE_GOOGLEMAPS='';

?>